server:
  port: ${SERVER_PORT:8761}

spring:
  application:
    name: ${APPLICATION_NAME:movie-services-registry}

eureka:
  client:
    register-with-eureka: ${REGISTER_WITH_EUREKA:false}
    fetch-registry: ${FETCH_REGISTRY:false}


management:
  endpoints:
    web:
      exposure:
        include: "*"

  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true